name: dotnet-db

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: localhost_dev
      MYSQL_USER: localhost_dev
      MYSQL_PASSWORD: localhost_dev
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--local-infile=1"

